name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: RajahmundrySravani
          outputs: |
  dist/github-contribution-grid-snake.svg?color_snake=#7DD3FC&color_dots=#0F172A,#075985,#0EA5E9,#38BDF8,#7DD3FC
  dist/github-contribution-grid-snake-dark.svg?color_snake=#7DD3FC&color_dots=#020617,#075985,#0EA5E9,#38BDF8,#7DD3FC3FC

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
